; PlatformIO Configuration File for Team Durnibar WRO 2026 ESP32 Firmware
; Board: ESP32 NodeMCU (esp32dev)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    ESP32Servo @ ^3.0.5
    Wire
    adafruit/Adafruit VL53L1X @ ^1.0.2
    adafruit/Adafruit BNO055 @ ^1.6.3
    adafruit/Adafruit Unified Sensor @ ^1.1.14
